### ISSUE TITLE
Errors building on MacOS 10.15.3

### ISSUE THREAD

**Issue by mself** [quicky2000/tartini#29]
I'd very much like to help out with this project!

I'm trying to build it on MacOS 10.15.3 but am running into this issue.  The first ~15 files compile fine, but when compiling `drawwidget.cpp`, I get this error:

`In file included from widgets/drawwidget.cpp:1:
In file included from /Users/Matthew/Projects/Whistle/Tartini/tartini-master/include/static.h:3:
In file included from /usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/Qt:1:
In file included from /usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qnamespace.h:43:
In file included from /usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qglobal.h:142:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:2567:5: error: static_assert failed due to requirement
      '__is_forward_iterator<large_vector<AnalysisData>::iterator>::value' "std::max_element requires a ForwardIterator"
    static_assert(__is_forward_iterator<_ForwardIterator>::value,
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
widgets/drawwidget.cpp:770:53: note: in instantiation of function template specialization
      'std::__1::max_element<large_vector<AnalysisData>::iterator, lessValue>' requested here
  large_vector<AnalysisData>::iterator l_err = std::max_element(p_channel->dataIteratorAtChunk(l_start_chunk), p_channel->dataIteratorAtC...
                                                    ^
`
It seems like this is a conflict between Qt (5.14.1) and clang++ (11.0.3) related to the C++ Standard Library?  I've looked online, but can't find anything.  I uninstalled and reinstalled Qt.

**Comment by quicky2000** [comment]
Hi,

Thanks for this clear bug report !
I don't think this is related to Qt.
For me it is related to custom iterator defined in **general/large_vector.h:46**
This iterator does not define any type_traits so for compiler this not a **ForwardIterator** as required by **std::max_element** called at **widgets/drawwidget.cpp:770**
I tried to derive this custom iterator from **std::iterator** to provide **type_traits** info. I hope that by this way clang will recognise it as a **ForwardIterator**.
Could you try to compile branch **issue_29** and let me know the result ?

**Comment by quicky2000** [comment]
I tested on https://wandbox.org/ with CLang 11.0.0 and previous code compilation failed with a message similar to the one you indicated:
`/opt/wandbox/clang-head/include/c++/v1/algorithm:2595:5: error: static_assert failed due to requirement '__is_cpp17_forward_iterator<large_vector<unsigned int>::iterator>::value' "std::max_element requires a ForwardIterator"
    static_assert(__is_cpp17_forward_iterator<_ForwardIterator>::value,
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
prog.cc:338:56: note: in instantiation of function template specialization 'std::__1::max_element<large_vector<unsigned int>::iterator, (lambda at prog.cc:338:103)>' requested here`

With my modification it compiles successfully so I hope it will be the same for you.
Let me know the result

**Comment by mself** [comment]
Yes, with your modification the app compiles and builds fine now.  The app runs, but it crashes when I open any .wav file (I tested using the [example.wav](https://miracle.otago.ac.nz/tartini/download/wav/example.wav) on the Tartini web site).  I get an assertion failure in `NoteData::addVibratoData`:

```
114:            myassert(l_current_time + m_loop_step < (int)m_channel->get_pitch_lookup_smoothed().size());
```

```
lldb) p l_current_time
(int) $3 = 1388
(lldb) p m_loop_step
(int) $4 = 44
(lldb) p m_channel->get_pitch_lookup_smoothed().size()
(uint) $5 = 720
```
Backtrace:
```
  * frame #3: 0x00000001000ba84e tartini`NoteData::addVibratoData(this=0x00000001107102f8, p_chunk=44) at notedata.cpp:114:13
    frame #4: 0x0000000100015877 tartini`Channel::calcVibratoData(this=0x00000001038b54d0, p_chunk=44) at channel.cpp:1197:25
    frame #5: 0x0000000100091f7b tartini`MyTransforms::calculateAnalysisData(this=0x00000001038913d0, p_chunk=44, p_channel=0x00000001038b54d0) at mytransforms.cpp:564:24
    frame #6: 0x00000001000106cc tartini`SoundFile::calculateAnalysisData(this=0x00000001038913a0, p_chunk=44, p_channel=0x00000001038b54d0) at soundfile.hpp:186:21
    frame #7: 0x00000001000104e7 tartini`Channel::processNewChunk(this=0x00000001038b54d0, p_filter_state=0x00007ffeefbfca60) at channel.cpp:325:15
    frame #8: 0x000000010002b0e5 tartini`SoundFile::readChunk(this=0x00000001038913a0, p_n=32) at soundfile.cpp:529:26
    frame #9: 0x000000010002b722 tartini`SoundFile::preProcess(this=0x00000001038913a0) at soundfile.cpp:662:11
```

This crash only happens when I have "Do detailed pitch analysis" selected in preferences.

**Comment by mself** [comment]
This appears to be the same issue as #28.  It happens 100% of the time for me with [example.wav](https://miracle.otago.ac.nz/tartini/download/wav/example.wav) when "Do detailed pitch analysis" is selected in preferences.

**Comment by quicky2000** [comment]
OK nice to read that compilation issue is solved
It is also a good news to know that the runtime issue occur when opening a wave file.
I don't have the issue with the same example file but it will allow to compare your execution and mine.
Let switch on issue #28 for this topic
