### ISSUE TITLE
Port to RtAudio 5.1.0

### ISSUE THREAD

**Issue by mself** [quicky2000/tartini#34]
I'm investigating porting from RtAudio 3.0.3 (~2005) to 5.1.0 (~2019) to support Mac.

The task is to replace `RtAudio.*` with the new versions and modify `audioStream.*` to account for changes to the API.  I have a `rtaudio_5.1` branch at [`mself/tartini`](https://github.com/mself/tartini) where I'm doing a trial upgrade.

The main challenge is that the [RtAudio 5.1 API](https://www.music.mcgill.ca/~gary/rtaudio/index.html) only supports the callback interface, whereas the [RtAudio 3.0 API](http://web.mit.edu/carrien/Public/speechlab/marc_code/ADAPT_VC/rtaudio/doc/html/index.html) supported both callback and blocking APIs.  Unfortunately, Tartini uses the blocking API, so it is a significant change to move to the callback API.

I'll post updates here as I continue to make progress or need help!

**Comment by quicky2000** [comment]
Ok nice, keep me in touch of your progress !
I will try to look at API on my side too

**Comment by mself** [comment]
I wrote to the maintainer of RtAudio for some advice, and I got this reply:

> Hi Matthew,
> 
> Generally, it isn’t very robust to try to implement a blocking scheme on top of a callback scheme and I would recommend trying to update the program to use a callback scheme. However, if you want to try to make the blocking scheme work, you can look at (or just use) the RtWvOut class in STK: https://github.com/thestk/stk/blob/master/include/RtWvOut.h
> 
> Regards,
> 
> —gary

**Comment by mself** [comment]
Despite Gary's feedback, I am working on preserving the blocking interface to `AudioStream`, while converting to use the callback interface to `RtAudio`.  The alternative would change the interface to `AudioStream`, which would require deeper changes to Tartini.

For example, when playing back an audio file, Tartini "pushes" the audio to the `AudioStream`.  But it would need to be turned around so that the `AudioStream` pulls the data from the `AudioThread` in Tartini.  I'm not comfortable making such deep changes.

**Comment by mself** [comment]
I created PR #35 with a first implementation.  Please let me know if this works at all on Linux.

**Comment by quicky2000** [comment]
I will test it when it will rebased on master, there are more merge commit than commit making it difficult to follow what is meaningful or not

**Comment by mself** [comment]
I couldn't figure out how to clean up the commits in that branch, so I just created a new branch and a new PR.

**Comment by mself** [comment]
It builds fine on Mac, but is failing the Travis builds.  The compile errors appear to be related to include files needed by the new RtAudio files.

**Comment by mself** [comment]
I think it is trying to build the OSS version of RtAudio rather than the ALSA version?

**Comment by quicky2000** [comment]
> I couldn't figure out how to clean up the commits in that branch, so I just created a new branch and a new PR.

You just have to perform
> git rebase master

**Comment by quicky2000** [comment]
> I think it is trying to build the OSS version of RtAudio rather than the ALSA version?

I have exactly the same compilation errors on my side.
Some include directive are missing.
CMakeLists.txt and pitch.pro have define to build both OSS and ALSA

**Comment by quicky2000** [comment]
By removing the define related to OSS I succceed to compile but when I try to play example.wav I have a crash:
```
Opening file: /media/data/Programmation/C++/Git_repositories/tartini/example.wav
(FilteredFilename: /media/data/Programmation/C++/build/tartini/cmake-build-debug_new/temp002.wav)
File: channels=1, freq=44100, bits=16
channels = 1
channel size = 2048
----------Opening------------
filename = /media/data/Programmation/C++/Git_repositories/tartini/example.wav
rate = 44100
channels = 1
bits = 16
windowSize = 2048
stepSize = 1024
-----------------------------
File: channels=1, freq=44100, bits=16
AudioStream::open(p_mode = 2, p_freq = 44100, p_channels = 1, p_buffer_size = 1024
AudioStream::getOutputDeviceNames()

RtApiAlsa::getDeviceInfo: device ID is invalid!

Output Device 0: Default
AudioStream::getDeviceNumber(p_device_name="Default")
AudioStream::callback(nBufferFrames=1024, streamTime=0,000000, m_out_buffer.size()=0, m_in_buffer.size()=0)
Audio thread created for
Playing file /media/data/Programmation/C++/Git_repositories/tartini/example.wav
Assert Failed: success in /media/data/Programmation/C++/Git_repositories/tartini/rtAudio/audio_stream.cpp line 186.
Causing a trace crash.
```

**Comment by mself** [comment]
Glad it's compiling now.  What do you see in the settings dialog?  Do you see both input and output devices in the audio tab?  If so, trying selecting them explicitly rather than using "default".  I'm not sure that the logic for "default" is working correctly.

**Comment by mself** [comment]
I get this output:
```
QT_VERSION_STR="5.14.1"
QT_VERSION=50e01
QWT_VERSION_STR="6.1.4"
QWT_VERSION=60104
2020-04-25 13:21:26.349358-0700 tartini[21543:274292] [qt.qpa.fonts] Populating font family aliases took 446 ms. Replace uses of missing font family "AnyStyle" with one that exists to avoid this cost.
Opening file: /Users/Matthew/Projects/Whistle/Sample Whistles/example.wav
(FilteredFilename: /Users/Matthew/Projects/Whistle/Tartini/tartini/Debug/temp018.wav)
File: channels=1, freq=44100, bits=16
channels = 1
channel size = 2048
----------Opening------------
filename = /Users/Matthew/Projects/Whistle/Sample Whistles/example.wav
rate = 44100
channels = 1
bits = 16
windowSize = 2048
stepSize = 1024
-----------------------------
File: channels=1, freq=44100, bits=16
AudioStream::open(p_mode = 2, p_freq = 44100, p_channels = 1, p_buffer_size = 1024
AudioStream::getOutputDeviceNames()
2020-04-25 13:21:41.067787-0700 tartini[21543:274292] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x6000002ade40> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2020-04-25 13:21:41.108728-0700 tartini[21543:274292]  HALC_ShellDriverPlugIn::Open: Can't get a pointer to the Open routine
2020-04-25 13:21:41.109255-0700 tartini[21543:274292]  HALC_ShellDriverPlugIn::Open: Can't get a pointer to the Open routine
2020-04-25 13:21:41.109614-0700 tartini[21543:274292]  HALC_ShellDriverPlugIn::Open: Can't get a pointer to the Open routine

RtApiCore::getDeviceInfo: device ID is invalid!

AudioStream::getDeviceNumber(p_device_name="Apple Inc.: Built-in Output")
Output Device 1: Apple Inc.: Built-in Output
Audio thread created for
Playing file /Users/Matthew/Projects/Whistle/Sample Whistles/example.wav
AudioStream::writeFloats(p_length=1024, p_ch=1, m_out_buffer.size()=0)
..........................................................................................................................................................................................................................................................................................AudioStream::callback(nBufferFrames=1024, streamTime=0.000000, m_out_buffer.size()=1024, m_in_buffer.size()=0)
AudioStream::writeFloats(p_length=1024, p_ch=1, m_out_buffer.size()=0)
...................AudioStream::callback(nBufferFrames=1024, streamTime=0.023220, m_out_buffer.size()=1024, m_in_buffer.size()=0)
AudioStream::writeFloats(p_length=1024, p_ch=1, m_out_buffer.size()=0)
..................AudioStream::callback(nBufferFrames=1024, streamTime=0.046440, m_out_buffer.size()=1024, m_in_buffer.size()=0)
AudioStream::writeFloats(p_length=1024, p_ch=1, m_out_buffer.size()=0)
....................AudioStream::callback(nBufferFrames=1024, streamTime=0.069660, m_out_buffer.size()=1024, m_in_buffer.size()=0)
AudioStream::writeFloats(p_length=1024, p_ch=1, m_out_buffer.size()=0)
...................AudioStream::callback(nBufferFrames=1024, streamTime=0.092880, m_out_buffer.size()=1024, m_in_buffer.size()=0)
AudioStream::writeFloats(p_length=1024, p_ch=1, m_out_buffer.size()=0)
....................AudioStream::callback(nBufferFrames=1024, streamTime=0.116100, m_out_buffer.size()=1024, m_in_buffer.size()=0)
...
AudioStream::writeFloats(p_length=1024, p_ch=1, m_out_buffer.size()=0)
....................AudioStream::callback(nBufferFrames=1024, streamTime=10.611519, m_out_buffer.size()=1024, m_in_buffer.size()=0)
AudioStream::writeFloats(p_length=1024, p_ch=1, m_out_buffer.size()=0)
.....................AudioStream::callback(nBufferFrames=1024, streamTime=10.634739, m_out_buffer.size()=1024, m_in_buffer.size()=0)
AudioStream::close()
```

**Comment by mself** [comment]
The calls to `AudioStream::writeFloats()` are where the app is writing data into the `RingBuffer` and the calls to `AudioStream::callback()` are where the audio interface is reading the data from the `RingBuffer` and playing it.  Note that each "." in the output represents a call to a 1ms sleep (`msleep(1)`).

If the app fails to write enough data to the `RingBuffer` before the audio interface attempts to read it, then you will get the assert that you are seeing.  

When I run it, you can see that the app writes the first buffer of data and then there is then a significant delay before the audio interface is ready to read it.  But after the first time, the app typically writes the data ~20ms before the audio interface is ready to read it, which is good.

In your case, it seems like the app is not writing any data before the audio interface needs the first buffer?

**Comment by mself** [comment]
I pushed a second commit that fixes issues with device numbers.  RtAudio 5.1 now uses 0-based device numbers whereas 3.0 used 1-based, so I had to make some changes.  The handling of default devices also changed, so I fixed that.

I split the previous "Default" pseudo device name into separate "Default Input" and "Default Output" ones, so you will probably need to open the settings dialog to pick one of the new legal values.

Please see if all of your expected input and output devices appear in the settings dialog and see if recording or playback now work for you on Linux.  I'm still getting garbled output on playback and silence when recording.  (The latter may be due to lack of the right entitlements on the Mac.)

**Comment by quicky2000** [comment]
Hi,

In settings dialogs I see input and output devices that look similar to what I have with RtAudio 3
However when selecting output device that works with RtAudio 3 I have the same issue than described above wheras with RtAudio 3 I have sound

```
Opening file: /media/data/Programmation/C++/Git_repositories/tartini/example.wav
(FilteredFilename: /media/data/Programmation/C++/build/tartini/cmake-build-debug_new/temp007.wav)
File: channels=1, freq=44100, bits=16
channels = 1
channel size = 2048
----------Opening------------
filename = /media/data/Programmation/C++/Git_repositories/tartini/example.wav
rate = 44100
channels = 1
bits = 16
windowSize = 2048
stepSize = 1024
-----------------------------
File: channels=1, freq=44100, bits=16
AudioStream::open(p_mode = 2, p_freq = 44100, p_channels = 1, p_buffer_size = 1024
AudioStream::getOutputDeviceNames()
num devices = 8
Probing device 0
Device 0: hw:HDA Intel PCH,0
  outs 2, ins: 2, duplex: 2, default out: 1, default in: 1, preferred rate: 48000
  found output device
Probing device 1
Device 1: hw:HDA Intel PCH,1
  outs 2, ins: 0, duplex: 0, default out: 0, default in: 0, preferred rate: 48000
  found output device
Probing device 2
Device 2: hw:HDA Intel PCH,3
  outs 8, ins: 0, duplex: 0, default out: 0, default in: 0, preferred rate: 48000
  found output device
Probing device 3
Device 3: hw:HDA Intel PCH,7
  outs 8, ins: 0, duplex: 0, default out: 0, default in: 0, preferred rate: 48000
  found output device
Probing device 4
Device 4: hw:HDA Intel PCH,8
  outs 8, ins: 0, duplex: 0, default out: 0, default in: 0, preferred rate: 48000
  found output device
Probing device 5
Device 5: hw:HDA Intel PCH,9
  outs 8, ins: 0, duplex: 0, default out: 0, default in: 0, preferred rate: 48000
  found output device
Probing device 6
Device 6: hw:HDA Intel PCH,10
  outs 8, ins: 0, duplex: 0, default out: 0, default in: 0, preferred rate: 48000
  found output device
Probing device 7
Device 7: default
  outs 32, ins: 32, duplex: 32, default out: 0, default in: 0, preferred rate: 48000
  found output device
AudioStream::getDeviceNumber(p_device_name="hw:HDA Intel PCH,0")
num devices = 8
Probing device 0
Device 0: hw:HDA Intel PCH,0
Output Device 0: hw:HDA Intel PCH,0
  outs 2, ins: 2, duplex: 2, default out: 1, default in: 1, preferred rate: 48000
  found matching device
Audio thread created for
AudioStream::callback(nBufferFrames=1024, streamTime=0,000000, m_out_buffer.size()=0, m_in_buffer.size()=0)
Playing file /media/data/Programmation/C++/Git_repositories/tartini/example.wav
Assert Failed: success in /media/data/Programmation/C++/Git_repositories/tartini/rtAudio/audio_stream.cpp line 186.
Causing a trace crash.

```

**Comment by mself** [comment]
I added a sleep in `AudioStream::callback()` that waits until there is enough output data in the `RingBuffer` to send.  It prints "+" characters when the audio interface is waiting for the app (as opposed to printing "." characters when the app is waiting for the audio interface).

Let me know if this fixes the problem.  If so, then there are significant timing differences between Linux and Mac, since this wait never happens on Mac.

**Comment by mself** [comment]
I tried removing OSS as a default option of Linux in order to fix the Travis build, but it didn't work.  Do you know how to get the Travis builds to work with RtAudio 5.1?

**Comment by quicky2000** [comment]
> I tried removing OSS as a default option of Linux in order to fix the Travis build, but it didn't work. Do you know how to get the Travis builds to work with RtAudio 5.1?

You have to remove -D__LINUX_OSS__ from CMakeLists.txt too

**Comment by quicky2000** [comment]
> I added a sleep in `AudioStream::callback()` that waits until there is enough output data in the `RingBuffer` to send. It prints "+" characters when the audio interface is waiting for the app (as opposed to printing "." characters when the app is waiting for the audio interface).
> 
> Let me know if this fixes the problem. If so, then there are significant timing differences between Linux and Mac, since this wait never happens on Mac.

Now playback is woking on Linux, recording works too, but play&record doesn't work

**Comment by mself** [comment]
OK, I think I fixed play and record!

Please check if everything is building and running properly on Linux.  Is there any way to see if the latency is as good as before?  And can you think of any stress tests to try to find edge case bugs?

If everything works on Linux, then there is some additional code cleanup I want to do before considering this done.

On the Mac, recording still isn't working for me (it just records silence).  But the data flow is all working and I think it is the mic entitlement issue.  That's not really related to porting to RtAudio 5.1.

**Comment by quicky2000** [comment]
> OK, I think I fixed play and record!
> 
> Please check if everything is building and running properly on Linux. 
> 

It buils properly but the stop of play&record don't work.
I see the print indicating that AudioStream is closed but the callback continue to execute and print "+" to indicate it is waiting. It prevent m_audio to be destroyed and Qt Interface is frozen
By adding a check on audio stream status at line 195, callback exit properly, RtAudio object is well destroyed and Qt interface give me the hand

```
QThread::msleep(1);
if(!m_audio->isStreamRunning())
{
   return 0;
}
```

> Is there any way to see if the latency is as good as before? And can you think of any stress tests to try to find edge case bugs?

I don't know how original developer of Tartini proceed. A way to evaluate would perhpas be to use C++ time API to evaluate execution time for each chunk ?

> If everything works on Linux, then there is some additional code cleanup I want to do before considering this done.
>

Ok for me
 
> On the Mac, recording still isn't working for me (it just records silence). But the data flow is all working and I think it is the mic entitlement issue. That's not really related to porting to RtAudio 5.1.

Do you have some ideas to get the entitlement ?

**Comment by mself** [comment]
I finally got recording working on the Mac.  It works when I build with Xcode, but not if you build with QtCreator.  But, in any case, it is working for me.  There are some complex interactions with Qt when you need to use custom Plist.info files.  Others who are more familiar with Qt on the Mac may be able to improve the solution.

**Comment by mself** [comment]
OK, I am all done with the port to RtAudio 5.1.  Can you check if everything is working as well as it was with 3.03 on Linux?  If so, it is ready to merge.

Everything works for me on Mac, but nothing worked at all before so I have nothing to compare it to :-)
