### ISSUE TITLE
"Harmonic Track" view doesn't work on Mac

### ISSUE THREAD

**Issue by mself** [quicky2000/tartini#54]
The "Harmonic Track" [view]( https://miracle.otago.ac.nz/tartini/doc/more_views.html) just shows black on the Mac.  Does it work on Linux?

![image](https://user-images.githubusercontent.com/6620480/80849339-9a34e080-8bcb-11ea-89b9-9eda6dd824e6.png)

**Comment by quicky2000** [comment]
Hi,

Here is what I have with example.wav
![Screenshot_20200502_141356](https://user-images.githubusercontent.com/3935099/80863853-35d35900-8c7f-11ea-90ac-fbd65f5b7d92.png)

**Comment by quicky2000** [comment]
Hi,

Here is what I have with examle.wav
Are you sure you recompile after I remove commit related to GluOrtho2D ?
![Screenshot_20200502_141643](https://user-images.githubusercontent.com/3935099/80863898-9367a580-8c7f-11ea-9059-5b9f6cf33557.png)

**Comment by mself** [comment]
Yes, this is with the old calls to `gluOrtho2D()` and `gluLookAt()`.  I don't think I've ever seen it work.  The other "harmonic" views all seem to work.

The "Pitch Compass" also doesn't seem to work.  It displays, but always points straight up and down.  
![image](https://user-images.githubusercontent.com/6620480/80871491-ca2ec300-8c61-11ea-8403-173e01a5ec9c.png)


And the "Cepstrum View" only sort-of works.  It shows alternating red/blue bands that change width and it displays the Period text.  But there is no chart line on it.
![image](https://user-images.githubusercontent.com/6620480/80871505-ddda2980-8c61-11ea-94d3-486ec2bb6a86.png)

**Comment by quicky2000** [comment]
> The "Pitch Compass" also doesn't seem to work. It displays, but always points straight up and down
Addressed in issue #66

**Comment by quicky2000** [comment]
> 
> And the "Cepstrum View" only sort-of works. It shows alternating red/blue bands that change width and it displays the Period text. But there is no chart line on it.
> ![image](https://user-images.githubusercontent.com/6620480/80871505-ddda2980-8c61-11ea-94d3-486ec2bb6a86.png)

It's the normal behaviour, if you move along example.wav you will band width increase of decrease according to period value

**Comment by mself** [comment]
The docs on the Tartini web site show that it should look like this:
![image](https://user-images.githubusercontent.com/6620480/81022704-2725a700-8e23-11ea-8590-8933ca0832dd.png)

**Comment by mself** [comment]
Never mind...  I now see that you only get the waveform in the Cepstrum View if you choose "MPM + Modified Cepstrum" in the Analysis tab of the Settings dialog.  The width of the colored bars is determined by the MPM analysis -- not the Cepstrum, which is a bit confusing.

Here's what I see when I do that:
![image](https://user-images.githubusercontent.com/6620480/81023682-fd21b400-8e25-11ea-8b3f-0c2701af290c.png)
