### ISSUE TITLE
Poor performance on Mac

### ISSUE THREAD

**Issue by mself** [quicky2000/tartini#55]
The app performance is pretty poor on Mac.  How does it compare on Linux?  Have any of the recent changes made anything worse?

Here's what I see playing [example.wav](https://miracle.otago.ac.nz/tartini/download/wav/example.wav) depending on the "Note Range" I choose in the Settings dialog:
- "Notes F1 and Higher" (24ms step size):  Audio plays and the UI keeps up
- "Notes F2 and Higher" (12ms step size):  Audio plays, but the UI falls behind
- "Notes F3 and Higher" (6ms step size):  "Stream output underflow!" errors and UI barely moves

**Comment by quicky2000** [comment]
It works properly with these different settings and example.wav
I see a huge difference in perf since a migrated to a laptop with an SSD

**Comment by mself** [comment]
I have an SSD, although the computer is a bit old (2013).  3.2 GHz Quad-Core Intel Core i5.

I'm going to add some timing measurements so that we can compare how long things certain sections take on your system vs. mine.

**Comment by mself** [comment]
I added timing of file preprocessing.  Here is what I see for `example.wav` when run at "F1 and Higher" and then at "F3 and Higher"
```
Pre-processing took 1033 ms for 460 chunks (2.24565 ms per chunk, 455992 frames/sec)
Pre-processing took 1102 ms for 1843 chunks (0.597938 ms per chunk, 428138 frames/sec)
```
In the second case there are 4x more chunks, but they are 1/4 the size, so the result is basically the same.

In any case,  this is very fast and is not the cause of the performance problems on the Mac.

**Comment by mself** [comment]
I also added timing of widget `paintEvent()` and `paintGL()` calls.

This did not reveal anything particularly slow.
```
4 ms: FreqWidgetGL::paintGL()
3 ms: VibratoWidget::paintGL()
1 ms: VibratoSpeedWidget::paintGL()
```

The others all showed as 0 ms (i.e. < 0.5 ms)

What numbers do you see?

**Comment by mself** [comment]
OK, I think I see the cause of the performance problem with using the "Notes F3 and higher" setting.  The widgets attempt to redraw after a certain number of buffers, which means that they draw faster (per unit time) for smaller buffers.

Certain widgets (like `VibratoCircleWidget`) seem to get priority, so they starve the other widgets.

This shows a count of how many times the paint methods were called while playing back the `example.wav` file from start to end with different buffer sizes.

```
Notes F0 and higher (Buffer size: 2048 frames)
  72 TimeAxis::paintEvent()
  72 AmplitudeWidget::paintGL()
  72 FreqWidgetGL::paintGL()
 121 VibratoSpeedWidget::paintGL()
 121 VibratoTimeAxis::paintEvent()
 121 VibratoWidget::paintGL()
 121 VolumeMeterWidget::paintEvent()
 204 VibratoTunerWidget::paintGL()
 230 VibratoCircleWidget::paintGL()

Notes F1 and higher (Buffer size: 1024 frames)
  73 TimeAxis::paintEvent()
  73 AmplitudeWidget::paintGL()
  73 FreqWidgetGL::paintGL()
 139 VibratoTimeAxis::paintEvent()
 139 VibratoWidget::paintGL()
 139 VolumeMeterWidget::paintEvent()
 326 VibratoSpeedWidget::paintGL()
 365 VibratoTunerWidget::paintGL()
 460 VibratoCircleWidget::paintGL()

Notes F2 and higher (Buffer size: 512 frames)
   7 TimeAxis::paintEvent()
   7 AmplitudeWidget::paintGL()
   7 FreqWidgetGL::paintGL()
   7 VibratoTimeAxis::paintEvent()
   7 VibratoWidget::paintGL()
   7 VolumeMeterWidget::paintEvent()
 517 VibratoSpeedWidget::paintGL()
 561 VibratoTunerWidget::paintGL()
 921 VibratoCircleWidget::paintGL()

Notes F3 and higher (Buffer size: 256 frames)
   4 TimeAxis::paintEvent()
   4 AmplitudeWidget::paintGL()
   4 FreqWidgetGL::paintGL()
   4 VibratoTimeAxis::paintEvent()
   4 VibratoWidget::paintGL()
   4 VolumeMeterWidget::paintEvent()
 473 VibratoSpeedWidget::paintGL()
 609 VibratoTunerWidget::paintGL()
1843 VibratoCircleWidget::paintGL()
```

Note that with F3, the `TimeAxis` widget (that's the bar along the very bottom) is only getting updated 4 times during the entire ~11sec playback.

I think the solution is to have the widgets adjust their update rate based on the buffer size so that they update at the same frequency independent of the buffer size.

**Comment by mself** [comment]
Here is some more info.  The widgets are updated at three different rates: `onChunkUpdate`, `onFastUpdate`, and `onSlowUpdate`:

```
onChunkUpdate() [47ms for F0, 23ms for F1, 12ms for F2, 6ms for F3]
- TunerView
- VibratoView -> m_vibrato_speed_widget
- VibratoView -> m_vibrato_circle_widget
- VibratoView -> m_vibrato_period_widget

onFastUpdate() [default = 75ms (13.3/sec)]
- SummaryDrawWidget
- HBlockView
- HStackWidget
- HBubbleWidget
- HCircleWidget
- VolumeMeterWidget
- PianoView
- FFTView
- CepstrumView
- ScoreView
- VibratoView -> m_vibrato_time_axis
- VibratoView -> m_vibrato_widget

onSlowUpdate() [default = 150ms (6.7/sec)]
- MainWindow -> m_time_slider
- MainWindow -> setNoteLabel
- MainWindow -> setChunkLabel
- MainWindow -> setTimeLabel
- FreqView -> m_freq_widget_GL
- FreqView -> m_amplitude_widget
- FreqView -> m_time_axis
- FreqView -> m_wave_widget
- HTrackView -> m_h_track_widget
- CorrelationView -> m_correlation_widget
```

The update rates for `onFastUpdate` and `onSlowUpdate` can be set in the Setting dialog.

The issue is that `onChunkUpdate` can become too fast for small chunk sizes.

My proposal is to add a third setting `onVeryFastUpdate` that can also be set in the Setting dialog.  It would default to 25ms (40/sec), which is very close to the value it has now for "Notes F1 and higher".  40 updates/sec is quite fast for UI updates.

This would ensure that the UI update rates are independent of the chunk size, so the app performance would not be affected by it.

**Comment by mself** [comment]
With the "Very fast updates" PR #65, the performance issues on the Mac are resolved.

This shows the new count of how many times the paint methods were called while playing back the `example.wav` file from start to end with different buffer sizes:

```
Notes F0 and higher (Buffer size: 2048 frames)
  73 AmplitudeWidget::paintGL()
  73 FreqWidgetGL::paintGL()
  73 TimeAxis::paintEvent()
 125 VibratoSpeedWidget::paintGL()
 141 VibratoTimeAxis::paintEvent()
 141 VibratoWidget::paintGL()
 141 VolumeMeterWidget::paintEvent()
 199 VibratoTunerWidget::paintGL()
 207 VibratoCircleWidget::paintGL()

Notes F1 and higher (Buffer size: 1024 frames)
  73 AmplitudeWidget::paintGL()
  73 FreqWidgetGL::paintGL()
  73 TimeAxis::paintEvent()
 143 VibratoTimeAxis::paintEvent()
 143 VibratoWidget::paintGL()
 143 VolumeMeterWidget::paintEvent()
 318 VibratoTunerWidget::paintGL()
 323 VibratoSpeedWidget::paintGL()
 329 VibratoCircleWidget::paintGL()

Notes F2 and higher (Buffer size: 512 frames)
  73 AmplitudeWidget::paintGL()
  73 FreqWidgetGL::paintGL()
  73 TimeAxis::paintEvent()
 142 VibratoTimeAxis::paintEvent()
 142 VibratoWidget::paintGL()
 142 VolumeMeterWidget::paintEvent()
 383 VibratoSpeedWidget::paintGL()
 389 VibratoTunerWidget::paintGL()
 408 VibratoCircleWidget::paintGL()

Notes F3 and higher (Buffer size: 256 frames)
  73 AmplitudeWidget::paintGL()
  73 FreqWidgetGL::paintGL()
  73 TimeAxis::paintEvent()
 144 VibratoTimeAxis::paintEvent()
 144 VibratoWidget::paintGL()
 144 VolumeMeterWidget::paintEvent()
 334 VibratoSpeedWidget::paintGL()
 394 VibratoTunerWidget::paintGL()
 417 VibratoCircleWidget::paintGL()
```

The rates are much more consistent across the buffer sizes.  The UI no longer stalls and there are no "Stream output underflow!" errors.

I think this fix works well, but it would be good to verify that the vibrato widgets still work as well as before.

**Comment by mself** [comment]
After testing this more, I think #65 needs a little more work.  It handles playback well, but doesn't handle the case where the user scrolls the timeline manually.  I think a little more refactoring of the update events is needed.  Still working on it...

**Comment by mself** [comment]
Note: To generate the stats above, enable `TIME_PAINT`, set the settings you want to test, and capture the logs from a playback of `example.wav` and put it in a file.  Then run:
```
cat timing-f1-new.log | colrm 1 6 | sort | uniq -c | sort -n
```
to see how many times each paint event occurred during the playback.

**Comment by mself** [comment]
> I added timing of file preprocessing. Here is what I see for `example.wav` when run at "F1 and Higher" and then at "F3 and Higher"
> 
> ```
> Pre-processing took 1033 ms for 460 chunks (2.24565 ms per chunk, 455992 frames/sec)
> Pre-processing took 1102 ms for 1843 chunks (0.597938 ms per chunk, 428138 frames/sec)
> ```
> 
> In the second case there are 4x more chunks, but they are 1/4 the size, so the result is basically the same.

What results do you get for this on your system with `TIME_PREPROCESS`?

**Comment by quicky2000** [comment]
Here are my results:

> Pre-processing took 197 ms for 460 chunks (0.428261 ms per chunk, 2.39107e+06 frames/sec)
> Pre-processing took 238 ms for 1843 chunks (0.129137 ms per chunk, 1.98239e+06 frames/sec)

**Comment by mself** [comment]
Wow.  That's ~5x faster.  If the same speed difference affects rendering then that could explain why I'm having problems with the UI being unresponsive and you are not.

Could it be caused by:
1. You have a faster CPU?  I have a 3.2 GHz Core i5 "Haswell" (I5-4570) supports AVX2
2. Your compiler is taking advantage of vector instructions and mine is not?
3. Reading the WAV file from disk is faster on your system?

**Comment by quicky2000** [comment]
> Wow. That's ~5x faster. If the same speed difference affects rendering then that could explain why I'm having problems with the UI being unresponsive and you are not.
> 

Same feeling

> Could it be caused by:
> 
>     1. You have a faster CPU?  I have a 3.2 GHz Core i5 "Haswell" (I5-4570) supports AVX2
> 
 i5 Quad Core Intel® Core™ i5-8265U (1,60GHz, 3,9GHz Turbo)

>     2. Your compiler is taking advantage of vector instructions and mine is not?
>
gcc 7.5 with options indicated in CMakeLists.txt
 
>     3. Reading the WAV file from disk is faster on your system?
1 To ADATA SX6000 Pro PCIe M.2 2280 (2100 Mo/R, 1500 Mo/W)
File system Ext 4
